# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31e988d6ec7ba3d8ab5df9a7af4a80c00700341ac9b2886c95bcc0ff141e59ded6bec570b8adec4abe74f2505c5ad91a1aac26f7cc5d77f0e525402130c84751

test:
  secret_key_base: c2cbef8aadaf71032416d4d9d7024d0f01f76a1fd42e3cc515a327b7c14c7e9990028a8b2099d413489d129fde63d9dca077bb84c7529c888f88ccb5886af333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
